version = 0.1
[default.deploy.parameters]
stack_name = "spare-room"
resolve_s3 = true
s3_prefix = "spare-room"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
parameter_overrides = "UserPoolAdminGroupName=\"apiAdmins\" UserPoolCustomerGroupName=\"apiCustomers\" UserPoolDomainName=\"spare-room\""
